main: me.Romindous.ZombieHunt.Main
name: ZombieHunt
version: 1.0
author: Romindous
api-version: 1.15

commands:
  zh:
    description: The command for ZombieHunt
  zkits:
    description: The command for ZombieHunt